name: Build mozc-ut AUR Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: pacman -Syu --noconfirm git base-devel sudo ibus

      - name: Create a non-root user
        run: |
          useradd -m u
          echo "u ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/u
          chown -R u:u .

      - run: sudo -u u bash -c "make waydroid"
      - run: sudo -u u bash -c "make mozc-ut"
      - run: sudo -u u bash -c "make ibus-mozc"
      - run: sudo -u u bash -c "make zoom"

      - run: ls -l mozc-ut ibus-mozc zoom waydroid
      - run: echo 'Run `sudo pacman -U /path/to/package.pkg.tar.zst` to install.' >> $GITHUB_STEP_SUMMARY


      - run: |
          mkdir -p packages
          mv mozc-ut/*.pkg.tar.zst ibus-mozc/*.pkg.tar.zst zoom/*.pkg.tar.zst packages/
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: packages
