name: Build mozc-ut AUR Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: pacman -Syu --noconfirm git base-devel sudo
      - name: Create a build directory and add a non-root user
        run: |
          useradd -m u
          echo "u ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/u
          chown -R u:u .

      - run: sudo -u u bash -c "make mozc-ut"
      - run: ls mozc-ut
      - run: pacman -U --noconfirm mozc-ut/*.pkg.tar.zst
      - run: pacman -S --noconfirm ibus
      - run: sudo -u u bash -c "make ibus-mozc"

      - run: ls -l mozc-ut ibus-mozc
      - run: echo 'Run `sudo pacman -U /path/to/package.pkg.tar.zst` to install.' >> $GITHUB_STEP_SUMMARY

      - name: Upload packages
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: |
            mozc-ut/*.pkg.tar.zst
            ibus-mozc/*.pkg.tar.zst