name: Build mozc-ut AUR Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  mozc-ut:
    uses: ./.github/workflows/makepkg.yml
    with:
      name: mozc-ut
  ibus-mozc:
    uses: ./.github/workflows/makepkg.yml
    with:
      name: ibus-mozc