name: Build mozc-ut AUR Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker container
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux:latest
          options: --rm --workdir /build
          run: |
            # Update the package list and install dependencies
            pacman -Syu --noconfirm
            pacman -S --noconfirm git base-devel

            # Create a build directory and clone the mozc-ut AUR package
            mkdir -p /build
            cd /build
            git clone https://aur.archlinux.org/mozc-ut.git
            cd mozc-ut

            # Build the package
            makepkg -si --noconfirm

      - name: Upload built package
        uses: actions/upload-artifact@v3
        with:
          name: mozc-ut
          path: /build/mozc-ut/*.pkg.tar.zst
