name: Build mozc-ut AUR Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker container and build package
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux:latest
          options: --rm --workdir /build
          run: |
            # Update the package list and install dependencies
            pacman -Syu --noconfirm
            pacman -S --noconfirm git base-devel sudo

            # Create a build directory and add a non-root user
            mkdir -p /build
            useradd -m builder
            echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder
            chown -R builder:builder /build

            # Switch to the non-root user and build the package
            sudo -u builder bash -c '
              cd /build
              git clone https://aur.archlinux.org/mozc-ut.git
              cd mozc-ut
              makepkg -si --noconfirm
            '

      - name: Upload built package
        uses: actions/upload-artifact@v3
        with:
          name: mozc-ut
          path: /build/mozc-ut/*.pkg.tar.zst
